name: Ubuntu NoMachine + Tailscale

on:
  workflow_dispatch:

jobs:
  nx:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install Desktop
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies dbus-x11

    - name: Download NoMachine (TAR.GZ)
      run: |
        curl -L -A "Mozilla/5.0" \
        https://web9001.nomachine.com/download/9.3/Linux/nomachine_9.3.7_1_x86_64.tar.gz \
        -o nomachine.tar.gz

    - name: Install NoMachine
      run: |
        tar -xzf nomachine.tar.gz
        cd nomachine*
        sudo ./nxserver --install

    - name: Start NoMachine
      run: |
        sudo /etc/NX/nxserver --start

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Start Tailscale
      run: |
        sudo tailscaled &
        sleep 5
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Show connection info
      run: |
        echo "NoMachine Port: 4000"
        echo "IP:"
        tailscale ip -4
        sleep infinity
