name: Ubuntu NoMachine + Tailscale

on:
  workflow_dispatch:

jobs:
  nx:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Update
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies curl snapd

    - name: Install NoMachine (snap)
      run: |
        sudo snap install nomachine --classic

    - name: Create user
      run: |
        sudo useradd -m user
        echo "user:user" | sudo chpasswd
        sudo usermod -aG sudo user

    - name: Desktop session
      run: |
        echo "exec startxfce4 &" | sudo tee /home/user/.xsession
        sudo chown user:user /home/user/.xsession

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Start Tailscale
      run: |
        sudo tailscaled &
        sleep 5
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Info
      run: |
        echo "USER: user"
        echo "PASS: user"
        echo "PORT: 4000"
        tailscale ip -4
        sleep infinity
